Repository stolostron/insights-metrics, pull requests merged in 2022-07, with the labels that each got.

#44 Imagescan Rebuild: 2022-07-05
  README.md
Labels: lgtm, dco-signoff: yes

#48 [release-2.5] Triggering image rebuild
  README.md
Labels: dco-signoff: yes

#51 update to go 1.18
  Dockerfile
  Makefile
  Makefile.prow
  build/.golangci.yml
  build/run-lint-check.sh
  go.mod
  go.sum
Labels: lgtm, approved, dco-signoff: yes

#52 remove lint config
  Makefile
  Makefile.prow
  build/.golangci.yml
  build/run-lint-check.sh
Labels: lgtm, approved, dco-signoff: yes

#50 [release-2.5] Updated OWNERS file approvers
  OWNERS
Labels: lgtm, approved, dco-signoff: yes
